---
title: "An Emergency: Global Warming"
date: '2020-10-20'
description: An Emergency Global Warming
draft: no
image: pic10.jpg
keywords: ''
slug: blog7
categories:
- ''
- ''
---



<div id="an-emergency-global-warming" class="section level1">
<h1>An Emergency: Global Warming</h1>
<div id="analysing-climate-change-and-temperature-anomalies" class="section level2">
<h2>Analysing Climate Change and Temperature Anomalies</h2>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>Firstly, we need to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>Then we select the year and the months from the ‘weather’ dataset and convert it to a long format.</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;%
  select(c(Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec))%&gt;%
  pivot_longer(cols = 2:13, names_to = &quot;Month&quot;, values_to = &quot;delta&quot;)
glimpse(tidyweather)</code></pre>
<pre><code>## Rows: 1,680
## Columns: 3
## $ Year  &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 188…
## $ Month &lt;chr&gt; &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, …
## $ delta &lt;dbl&gt; -0.54, -0.38, -0.26, -0.37, -0.11, -0.22, -0.23, -0.24, -0.26, …</code></pre>
<p>We observe that the dataframe has 3 variables: Year, Month, and Delta (Temperature Deviation)</p>
</div>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    subtitle = &quot;Weather Anomalies&quot;, 
    title = &quot;Weather is becoming warmer and warmer&quot;
  )+
  xlab(&quot;Date&quot;)+
  ylab(&quot;Temperature Deviation per month&quot;)</code></pre>
<p><img src="/blogs/blog7_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We create a scatter plot for each month.</p>
<p><img src="/blogs/blog7_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Looking at the plot we created, we observe that delta is increasing over time for all months. However, it seems that this increase is more pronounced in Winter. For instance, in October - March, the delta is closer to 1.5, whereas in the summer months it is around 1.</p>
<p>We would like to group the data into different time periods to study the large historical data. The most convenient way to do this is to refer to decades such as 1980s, 1990s etc. NASA calculates the temperature anomalies, as differed from the base period of 1951-1980. Thus, we create a new data frame called <code>comparison</code> that groups data in 5 time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove the data before 1800 and use <code>mutate</code> function to create a new variable <code>intervals</code> which contains information on which period each observation belongs to. We used <code>case_when()</code> to assign different periods.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;% 
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) + 
  theme_bw() +          
  labs (
    title = &quot;Delta gets more positive over the decades&quot;,
    subtitle = &quot;Density Plot for Monthly Deltas (Temparature Anomalies)&quot;,
    y     = &quot;Density&quot; ,
    x= &quot;Delta&quot;
  )</code></pre>
<p><img src="/blogs/blog7_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>avg_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%  
  # creating summaries for mean delta 
  summarise(annual_avg_delta = mean(delta, na.rm=TRUE)) 
ggplot(avg_annual_anomaly, aes(x=Year, y= annual_avg_delta))+
  geom_point()+
  geom_smooth() +
  theme_bw() +
  labs (
    title=&quot;Average yearly anomaly has been increasing exponentially since the 1960s&quot;,
    subtitle = &quot;Average Yearly Temparature Anomaly (Delta)&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/blogs/blog7_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.
Now, we construct a 95% confidence interval for our data.</p>
</blockquote>
<pre class="r"><code>calculate_ci &lt;- comparison %&gt;% 
  filter(interval == &quot;2011-present&quot;)%&gt;%
  summarise(mean_diff=mean(delta,na.rm = TRUE),
            sd_diff=sd(delta, na.rm = TRUE), 
            count_diff=n(), 
            se_diff=sd_diff/sqrt(count_diff), 
            t_critical = qt(0.975, count_diff-1),
            lower = mean_diff-t_critical*se_diff,
            upper = mean_diff+t_critical*se_diff)
#print out formula_CI
calculate_ci</code></pre>
<pre><code>## # A tibble: 1 x 7
##   mean_diff sd_diff count_diff se_diff t_critical lower upper
##       &lt;dbl&gt;   &lt;dbl&gt;      &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.966   0.262        108  0.0252       1.98 0.916  1.02</code></pre>
<p>The 95% confidence interval for delta is 0.916-1.02.</p>
<p>Now, we use the bootstrap method to create a confidence interval.</p>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
library(infer)
set.seed(1234)
data_infer &lt;- comparison %&gt;%
   filter(interval == &quot;2011-present&quot;)%&gt;%
  specify(response = delta)%&gt;%
  generate(reps = 1000, type=&quot;bootstrap&quot;)%&gt;%
  calculate(stat=&quot;mean&quot;)
percentile_ci &lt;- data_infer %&gt;%
  get_confidence_interval(level=0.95, type=&quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.917     1.02</code></pre>
<p>We have created two confidence intervals using two methods, one using our dataset and the other via bootstrapping for mean delta. The bootstrap method generates 1000 samples with replacement and approximates the distribution to estimate sample variability. The data shows us (for both methods, with the formula as well as with the infer package) that we can be 95% sure that the real mean of the population of temperature differences lies between 0.917 and 1.02.</p>
</div>
</div>
